services:
  powerpulse:
    container_name: app
    image: powerpulse:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=powerpulse;Username=powerpulse;Password=powerpulse

  postgres:
    container_name: db_postgres
    image: timescale/timescaledb:2.14.2-pg16
    environment:
      POSTGRES_USER: powerpulse
      POSTGRES_PASSWORD: powerpulse
      POSTGRES_DB: powerpulse
    volumes:
      - postgres-data:/var/lib/postgresql/data

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_DATE_FORMATS_FULL_DATE='DD-MM-YYYY'

volumes:
  postgres-data: